spring:
  datasource:
    name: tjb  #数据库名
    url: jdbc:mysql://localhost:3306/tjb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8 #url
    username: root  #用户名
    password: zzmzzm521  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #JDBC驱动
    type: com.alibaba.druid.pool.DruidDataSource

server:
  servlet:
    context-path: /admin # 项目根路径

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.tjb.lab1.bean #配置实体类

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql